[MOSIP-25064] Updated helm to enable prometheus scraping for regproc stage groupes
mosip/mosip-helm pull request #373
Opened 2023-03-02 08:25 UTC by akilalakshmanan

2023-03-02 09:46 UTC, syedsalman3753 requested changes

2023-03-02 09:46 UTC, syedsalman3753 commented on charts/regproc-group2/templates/service.yaml
> +    - name: securezone
do not hardcode values.

please pass it via values.yaml in range format as used for other services.yaml

2023-03-02 10:28 UTC, syedsalman3753 requested changes

2023-03-02 10:28 UTC, syedsalman3753 commented on charts/regproc-group2/templates/service.yaml
> +  - name: {{ $ep.port_name }}
target port is missing

2023-03-02 10:28 UTC, syedsalman3753 commented on charts/regproc-group2/values.yaml
>      port: 8090
add target ports

2023-03-02 10:28 UTC, syedsalman3753 commented on charts/regproc-group3/templates/service.yaml
> +  - name: {{ $ep.port_name }}
target port is missing

2023-03-02 10:28 UTC, syedsalman3753 commented on charts/regproc-group3/values.yaml
> +      port_name: abishandler
add target port as well

2023-03-02 10:28 UTC, syedsalman3753 commented on charts/regproc-group4/templates/service.yaml
> +  - name: {{ $ep.port_name }}
The target port is missing

Add the target ports for all server yamls and endpointList

2023-03-02 14:24 UTC, syedsalman3753 approved these changes

2023-03-03 09:16 UTC, ckm007 approved these changes

2023-03-03 09:19 UTC, merged