[DSD-2392] Added testrigs-cron helm chart.
mosip/mosip-helm pull request #429
Opened 2023-04-19 09:42 UTC by Mohanraj209

2023-04-21 05:14 UTC, syedsalman3753 requested changes
Please rename the chart with 'restart-deployment-cronjob`

2023-04-21 05:14 UTC, syedsalman3753 commented on charts/testrigs-cron/templates/cronjob.yaml
> +                      kubectl rollout restart deployment {{ .Values.deployments.deploymentName_2 }} -n {{ .Values.namespaces.namespace_2 }}"
Please add the rollout status check 

```kubectl -n $NS rollout status deployment/deployment-name```

2023-04-21 05:14 UTC, syedsalman3753 commented on charts/testrigs-cron/templates/cronjob.yaml
> +  concurrencyPolicy: Replace
reason why concurrencyPolicy is set to replace?

2023-04-25 04:16 UTC, Rakshitha650 approved these changes

2023-04-25 04:54 UTC, ckm007 commented on charts/dslorchestrator/values.yaml
> +      TESTLEVEL: "full,sanity"
remove this as it is not getting used in templates.

2023-04-25 04:56 UTC, ckm007 commented on charts/testrigs-cron/Chart.yaml
> +description: A Helm chart to deploy dslorchestrator to test working of MOSIP modules
update the description

2023-05-02 03:42 UTC, closed without merging