[DSD-2390] Added 2 Cron Jobs For DSL Run.
mosip/mosip-helm pull request #440
Opened 2023-05-02 04:03 UTC by Mohanraj209

2023-05-03 06:23 UTC, syedsalman3753 requested changes

2023-05-03 06:23 UTC, syedsalman3753 commented on charts/dslorchestrator/values.yaml
> +  - name: full
add `suspend: false` for full testlevel and
add `suspend: false` for sanity testlevel

2023-05-03 06:23 UTC, syedsalman3753 commented on charts/dslorchestrator/templates/cronjob.yaml
>    successfulJobsHistoryLimit: 1  # remove jobs which are successfully executed
add `suspend:` and templatize value based on level

2023-05-03 07:00 UTC, syedsalman3753 requested changes

2023-05-03 12:06 UTC, syedsalman3753 approved these changes

2023-05-04 03:57 UTC, ckm007 commented on charts/dslorchestrator/templates/cronjob.yaml
> +  {{- else }}
Can we have nested if check here instead of if and else statement.

2023-05-04 04:18 UTC, closed without merging