[DSD-2390] Updated dslorchestrator chart.
mosip/mosip-helm pull request #445
Opened 2023-05-05 04:30 UTC by Mohanraj209

2023-05-05 04:51 UTC, syedsalman3753 requested changes

2023-05-05 04:51 UTC, syedsalman3753 commented on charts/dslorchestrator/templates/cronjob.yaml
> +                  {{- range $.Values.extraEnvVarsSecret }}
Please remove env section from init-containers

2023-05-05 04:54 UTC, syedsalman3753 commented on charts/dslorchestrator/templates/cronjob.yaml
> +                  {{- range $.Values.extraEnvVarsSecret }}
also, test the deployment and run on the orchestrator

2023-05-05 11:57 UTC, syedsalman3753 commented on charts/dslorchestrator/templates/cronjob.yaml
>                envFrom:
remove envFrom section from init-containers

2023-05-08 05:02 UTC, syedsalman3753 approved these changes

2023-05-08 13:13 UTC, ckm007 approved these changes

2023-05-08 13:13 UTC, merged