[MOSIP-25305]Updated service name by removing utiltiy.
mosip/mosip-helm pull request #451
Opened 2023-05-13 11:16 UTC by Mohanraj209

2023-05-13 11:41 UTC, syedsalman3753 approved these changes

2023-05-13 11:42 UTC, syedsalman3753 requested changes

2023-05-13 11:42 UTC, syedsalman3753 commented on charts/regproc-landingzone/values.yaml
> +    path: /registrationprocessor/v1/landingzone/actuator/health
Is probe health url changed?

2023-05-17 07:56 UTC, sowmya695 approved these changes

2023-05-17 08:56 UTC, merged