DSD-2602 created helm chart for bqat service
mosip/mosip-helm pull request #462
Opened 2023-05-29 09:20 UTC by bhumi46

2023-05-29 11:31 UTC, ckm007 commented on charts/bqat-sdk/Chart.yaml
> +version: 12.0.1-B3
since this is first version. Lets make the chart version to 1.0.0.

2023-05-29 14:17 UTC, syedsalman3753 requested changes
can you confirm if the deployment has been tested?

2023-05-29 14:17 UTC, syedsalman3753 commented on charts/bqat-sdk/Chart.yaml
> +description: A Helm chart for MOSIP Auditmanager module
please update description

2023-05-29 14:17 UTC, syedsalman3753 commented on charts/bqat-sdk/Chart.yaml
> +  - kernel
please remove kernel from here as kernel has no link to sdk

2023-05-30 04:09 UTC, syedsalman3753 approved these changes

2023-05-30 05:57 UTC, ckm007 approved these changes

2023-05-31 11:27 UTC, syedsalman3753 approved these changes

2023-05-31 11:27 UTC, syedsalman3753 approved these changes

2023-06-01 12:16 UTC, merged