Develop
mosip/mosip-helm pull request #495
Opened 2023-07-20 18:43 UTC by Prafulrakhade

2023-07-21 04:48 UTC, syedsalman3753 requested changes

2023-07-21 04:48 UTC, syedsalman3753 commented on charts/config-server/templates/_overides.tpl
>        key: esignet-captcha-secret-key
Please remove the esignet captcha block.
Add have to add it via esignet's install.sh

2023-07-21 08:04 UTC, ckm007 commented on charts/prereg-application/values.yaml
> +    - uri:
this is not required.

2023-07-21 12:11 UTC, syedsalman3753 approved these changes

2023-07-24 08:32 UTC, ckm007 approved these changes

2023-07-24 08:32 UTC, merged